version: "3.8"

services:
  db:
    container_name: santander-instance
    image: postgres:latest
    environment:
      - POSTGRES_DB=santander
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
  santander-api:
    container_name: santander-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      app-network:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/santander
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: on-failure
networks:
  app-network:
    driver: bridge